#!/usr/bin/env bash

# When connecting to a synergy server as a client change the keyboard layout to the original.
function sc() {
	synergyc $1 && setxkbmap $(setxkbmap -query | grep "^layout:" | awk -F ": *" '{print $2}')
}

# Using nmcli, take connection name and device name and connect to that.
function con() {
    if [ $# -eq 0 ]
    then
        echo "No arguments were given. You need to atleast provide the access-point name."
        return
    fi

    if [ $# -eq 1 ]
    then
        nmcli -p con up "$1" ifname wlp2s0
    else
        nmcli -p con up "$1" ifname $2
    fi
}
